---
- name: Kontrollige, kas vajalik tarkvara on paigaldatud
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Kontrolli, kas SNMPD või net-snmp on paigaldatud
      ansible.builtin.package:
        name: "{{ 'net-snmp' if ansible_facts['os_family'] in ['RedHat', 'Suse'] else 'snmpd' }}"
        state: present

    - name: Kontrolli, kas TMUX, MC, WGET, TREE, GIT on paigaldatud
      ansible.builtin.package:
        name:
          - tmux
          - mc
          - wget
          - tree
          - git
        state: present

- name: Kontrolli, kas vajalik tarkvara on paigaldatud ainult mart-ansible VM-i
  hosts: Ansible
  become: yes
  tasks:
    - name: Kontrolli, kas Ansible, sshpass, yamlint, ansible-lint on paigaldatud
      ansible.builtin.package:
        name:
          - ansible
          - sshpass
          - yamllint
          - ansible-lint
        state: present

- name: Kontrolli, kas vajalik tarkvara on paigaldatud ainult mart-dockerhost VM-i
  hosts: Docker
  become: yes
  tasks:
    - name: Kontrolli, kas Docker on paigaldatud
      ansible.builtin.package:
        name: docker-ce
        state: present
