---
- name: Kontrollige, kas vajalik tarkvara on paigaldatud
  hosts: all
  become: yes
  tasks:
    - name: Kontrolli, kas snmpd on paigaldatud
      ansible.builtin.package:
        name: "{{ 'net-snmp' if ansible_facts['distribution'] == 'openSUSE' else 'snmpd' }}"
        state: present
      tags:
        - snmpd

    - name: Kontrolli, kas tmux on paigaldatud
      ansible.builtin.package:
        name: tmux
        state: present
      tags:
        - tmux

    - name: Kontrolli, kas mc on paigaldatud
      ansible.builtin.package:
        name: mc
        state: present
      tags:
        - mc

    - name: Kontrolli, kas wget on paigaldatud
      ansible.builtin.package:
        name: wget
